import Hero from "@/components/Hero/Hero";
import NewCollections from "@/components/NewCollections";
import NewLetter from "@/components/NewLetter";
import Offers from "@/components/Offers";
import Popular from "@/components/Popular";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Clotes Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <Popular />
        <Offers />
        <NewCollections />
        <NewLetter />
      </div>
    </>
  );
}
